version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: azs
      POSTGRES_USER: adm
      POSTGRES_PASSWORD: adm
    ports:
      - "5432:5432"
    networks:
      - minha_rede

  minha_app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/azs
      SPRING_DATASOURCE_USERNAME: adm
      SPRING_DATASOURCE_PASSWORD: adm
    ports:
      - "8080:8080"
    networks:
      - minha_rede

networks:
  minha_rede:
    driver: bridge
